### ISSUE TITLE
Calculate CHaMP Metrics for Yankee Fork 595

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/champ_metrics#1]
Please calculate CHaMP Topo metrics for the following single Yankee Fork site in 2018. Here's the data:

https://ecologicalresearchinc.box.com/s/cmzvdol1ed9br33gi8yozpgn4ff41ow1

This is a lingering site that needed rework by Boyd just before Christmas 2020 when I ran all the other sites.

ps I am happy to run this on my machine with your support. I just could get the venv to work. Deleted it. Ran the create venv shell script. It finished OK but then still couldn't find GDAL.

**Comment by MattReimer** [comment]
@philipbaileynar I think this is done no?
